### PR TITLE
Merge Simply Love 4.9

### LINKED ISSUE #56: Update to 4.9
[Release notes](https://github.com/quietly-turning/Simply-Love-SM5/releases/tag/4.9)
[Commit history](https://github.com/quietly-turning/Simply-Love-SM5/compare/4.8.7...4.9)

Port relevant features (in order of priority):
- [ ] Measure counter lookahead
- [ ] Color changes
- [ ] Stage count in course mode
- [ ] Profile avatars
- [ ] Italian language support
- [ ] Selectable hold judgments (maybe, if we have space in the options menu)
- [ ] Column spacing in pump
- [ ] Random Background behavior 

Apply fixes (in no particular order):
- [ ] Update Spanish translation
- [ ] Default Fail Setting bug
- [ ] QR code generator to work with ssc files

Review commit history and port other things that look relevant, noting them below.
Currently at commit: [c845ac3](https://github.com/quietly-turning/Simply-Love-SM5/commit/c845ac366ff60c3ba976f238cfd913b4a4d258df)
Things ported:

### PR DESCRIPTION
**Pull request by Roujo**
Things to check:
- [x] Some panes in the evaluation screen have moved during the merge
  - [x] Per-arrow judgments
  - [x] Records
- [x] Experiment with the 4.9-specific handling of aspect ratios and display resolutions
  - [x] Remove it from the theme if we're sticking with the current portrait-specific implementation
- [ ] Alignement issues. I don't know of any, but there's bound to be a couple. =P

Fixes #56

### CODE REVIEW

**Comment by Sereni** [comment]
Went through screens up to ScreenSelectMusic, and Player/Service options. Evaluation, evaluation summary, and name entry screens need attention.

**Comment by Sereni** [comment]
Tidied ScreenEvaluation a bit and looked at others. There are a few more issues remaining:

- [ ] ScreenGameplay: the event mode / stage x splash flies off the screen, should be displayed in bottom-right corner
- [ ] Evaluation: input handler should be reverted, and not handle input from other player's buttons, since there's no second pane. It doesn't revert cleanly though.
- [ ] Evaluation: QR code pane is gone and I can't figure out where D:
- [ ] Evaluation: TestInput pane was possibly never ported to vertical? Need to check and fix
- [ ] GameOver: avatar is out of place, and I'm not sure there is a place for it
- [ ] Profile screen: not a blocker, but when zoomed out via F3+E, there's a bunch of judgment font previews rendered off-screen...

**Comment by Roujo** [comment]
> TestInput pane was possibly never ported to vertical? Need to check and fix
I don't remember seeing it in the evaluation screen, in any case. It would be nice to have! ^^

> QR code pane is gone and I can't figure out where D:
I remember that part of the merge, I'll give it a look soon. =)

**Comment by Roujo** [comment]
Two more items:
- [ ] Evaluation: On the main pane, there's a space to the left of the score - maybe the grade is supposed to fit in there but it's missing since it was removed in Vertical? It'd be nice to have it back, IMO. =)
- [ ] Additional Player Options: The combo font and hold judgement previews are missing, I probably removed them accidentally in the merge.

**Comment by Sereni** [comment]
Thanks for flagging! The score had space because the correct size was lost in the merge. Brought it back. With this size, there's no space. I don't see toooo much value in the letter grade and I think it needs its own large area if we were to include it, otherwise it'd look crowded with the score. Prefer to keep it off for now.

Screen Shot 2020-07-15 at 5 44 38 AM
image

**Comment by Sereni** [comment]
Merging this now and following up on the rest of the issues in dev.

Thanks Roujo!

**Comment by Sereni** [comment]
@Roujo I had some fun finding the combo and hold previews. Got down to this: calls to `SCREENMAN:GetTopScreen()` in `Graphics/OptionRow Frame.lua` return nil if we're in the 2nd player options screen, but work correctly on the 1st screen. 

I also just realized that ExportOnChange doesn't work on the 2nd screen for some reason, which would make previews only update on Enter :( in addition to already breaking a few of our rows there.

**Pull request merged**
